config/routes.rb
Rails.application.routes.draw do
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  resources :students
  resources :blogs
  resources :courses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :student
  has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :description, presence: true
  has_and_belongs_to_many :students
  has_many :comments, as: :commentable
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :student
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :description, presence: true
  has_many :student_projects
  has_many :students, through: :student_projects
  has_many :comments, as: :commentable
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true
  validates :first_name, :last_name, length: {minimum: 2, maximum: 50}
  # validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: 'only letters are allowed'}

  has_many :blogs
  has_and_belongs_to_many :courses
  has_many :student_projects
  has_many :projects, through: :student_projects
  has_one :profile

  has_one_attached :photo

  after_create :age_calculation

  def age_calculation
    if self.date_of_birth.present?
      age = Date.today.year - self.date_of_birth.year
      puts "++++ Your age is #{age} ++++"
    else
      puts "+++ Cannot calculate age ++++"
    end
  end
end

app/models/student_project.rb
class StudentProject < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    
    if @blog.save
      redirect_to blogs_path, notice: "Blog has been created succesfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog), notice: "Blog has been updated succesfully"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "Blog has been deleted succesfully"
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path, notice: "Course has been created succesfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to course_path(@course), notice: "Course has been updated succesfully"
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path, notice: "Course has been deleted succesfully"
  end

  private
  def course_params
    params.require(:course).permit(:name, :description)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: "Student has been created succesfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to student_path(@student), notice: "Student has been updated succesfully"
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path, notice: "Student has been deleted succesfully"
  end

  private
  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :date_of_birth, :address, :contact, :photo)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/blogs/_form.html.erb
<%= form_with model: blog do |form| %>

    <% if @blog.errors.any? %>
        <% @blog.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
    <% end %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :content %>
        <%= form.text_field :content %>
    </div>
    <%= form.submit %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Student</h1>

<%=  render "form", blog: @blog %>

app/views/blogs/index.html.erb
<p><%=  notice %></p>

<h1>Blogs</h1>
<p><%= link_to "Create a blog", new_blog_path %></p>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th class="col-span-3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @blogs.each do |blog| %>
            <tr>
                <td><%= blog.title %></td>
                <td><%= blog.content %></td>
                <td><%= link_to "View", blog %></td>
                <td><%= link_to "Edit", edit_blog_path(blog) %></td>
                <td><%= link_to "Delete", blog, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/blogs/new.html.erb
<h1>New Blog</h1>


<%= render "form", blog: @blog %>

app/views/blogs/show.html.erb
<p><%=  notice %></p>
<h1>Blog Detail</h1>

<p><strong><%= @blog.title %></strong></p>
<p><%= @blog.content %></p>

<%= link_to "Back", blogs_path %> |
<%= link_to "Edit", edit_blog_path(@blog) %>

app/views/courses/_form.html.erb
<%= form_with model: course do |form| %>

    <% if @course.errors.any? %>
        <% @course.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
    <% end %>

    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_field :description %>
    </div>
    <%= form.submit %>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%=  render "form", course: @course %>

app/views/courses/index.html.erb
<p><%=  notice %></p>

<h1>Courses</h1>
<p><%= link_to "Create a course", new_course_path %></p>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th class="col-span-3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @courses.each do |course| %>
            <tr>
                <td><%= course.name %></td>
                <td><%= course.description %></td>
                <td><%= link_to "View", course %></td>
                <td><%= link_to "Edit", edit_course_path(course) %></td>
                <td><%= link_to "Delete", course, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/courses/new.html.erb
<h1>New Course</h1>


<%= render "form", course: @course %>

app/views/courses/show.html.erb
<p><%=  notice %></p>
<h1>Course Detail</h1>

<p><strong><%= @course.name %></strong></p>
<p><%= @course.description %></p>

<%= link_to "Back", courses_path %> |
<%= link_to "Edit", edit_course_path(@course) %>

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootcamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>

    <% if student.errors.any? %>
        <% student.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
    <% end %>

    <div class="form-group mt-3">
        <%= form.label :photo %>
        <%= form.file_field :photo %>
    </div>
    <div class="form-group mt-3">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control form-control-lg' %>
    </div>
    <div class="form-group mt-3">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control form-control-lg' %>
    </div>
    <div class="form-group mt-3">
        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control form-control-lg' %>
    </div>
    <div class="form-group mt-3">
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth, class: 'form-control form-control-lg' %>
    </div>
    <div class="form-group mt-3">
        <%= form.label :address %>
        <%= form.text_field :address, class: 'form-control form-control-lg' %>
    </div>
    <div class="form-group mt-3">
        <%= form.label :contact %>
        <%= form.text_field :contact, class: 'form-control form-control-lg' %>
    </div>
    <%= form.submit class: 'btn btn-primary mt-3'%>
<% end %>

app/views/students/edit.html.erb
<div class="col-lg-8 mx-auto mt-3">
    <div class="card shadow">
        <div class="card-header">
            <div class="card-title">
                <h1>Edit Student</h1>
            </div>
        </div>
        <div class="card-body">
            <%=  render "form", student: @student %>
        </div>
    </div>
</div>

app/views/students/index.html.erb
<p><%=  notice %></p>

<h1>Students</h1>
<p><%= link_to "Create New Student", new_student_path %></p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>DOB</th>
            <th>Address</th>
            <th>Contact</th>
            <th class="col-span-3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student| %>
            <tr>
                <td><%= student.first_name %></td>
                <td><%= student.last_name %></td>
                <td><%= student.email %></td>
                <td><%= student.date_of_birth %></td>
                <td><%= student.address %></td>
                <td><%= student.contact %></td>
                <td><%= link_to "View", student %></td>
                <td><%= link_to "Edit", edit_student_path(student) %></td>
                <td><%= link_to "Delete", student, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/students/new.html.erb
<div class="col-lg-8 mx-auto mt-3">
    <div class="card shadow">
        <div class="card-header">
            <h1 class="card-title">New Student</h1>
        </div>
        <div class="card-body">
        <%= render "form", student: @student %>
        </div>
    </div>
    
</div>

app/views/students/show.html.erb
<p><%=  notice %></p>
<h1>Student Detail</h1>

<%= image_tag @student.photo if @student.photo.attached? %>
<p><strong><%= @student.first_name %></strong></p>
<p><strong><%= @student.last_name %></strong></p>
<p><strong><%= @student.email %></strong></p>
<p><strong><%= @student.date_of_birth %></strong></p>
<p><strong><%= @student.address %></strong></p>
<p><strong><%= @student.contact %></strong></p>

<%= link_to "Back", students_path %> |
<%= link_to "Edit", edit_student_path(@student) %>